### ISSUE TITLE
Failed to create JavaScript extend wrapper for class on Android platform 5.4.0

### ISSUE THREAD

**Issue by radixcorp** [Pip3r4o/nativescript-android-utils#3]
The app runs fine on Android platform 5.2.0, but crashes after upgrading to 5.4.0:
```
System.err: java.lang.RuntimeException: Unable to start service com.radixdev.myproject.GeofenceTransitionsIntentService@8ecdab4 with Intent { cmp=com.radixdev.myproject/.GeofenceTransitionsIntentService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.app.IntentService$ServiceHandler.obtainMessage()' on a null object reference

System.err: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)

System.err: 	at android.app.ActivityThread.-wrap20(Unknown Source:0)

System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)

System.err: 	at android.os.Handler.dispatchMessage(Handler.java:105)

System.err: 	at android.os.Looper.loop(Looper.java:164)

System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6541)

System.err: 	at java.lang.reflect.Method.invoke(Native Method)

System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)

System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.app.IntentService$ServiceHandler.obtainMessage()' on a null object reference

System.err: 	at android.app.IntentService.onStart(IntentService.java:127)

System.err: 	at android.app.IntentService.onStartCommand(IntentService.java:141)

System.err: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)

System.err: 	... 8 more
```

**Comment by mitskovets** [comment]
I have the same problem, tns-android: 5.4.0

`java.lang.RuntimeException: Unable to start service com.something.SomeService@bff0672 with Intent { act=ACTION_START cmp=com.my.app/com.something.SomeService }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.app.IntentService$ServiceHandler.obtainMessage()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
	at android.app.ActivityThread.access$1600(ActivityThread.java:199)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.app.IntentService$ServiceHandler.obtainMessage()' on a null object reference
	at android.app.IntentService.onStart(IntentService.java:127)
	at android.app.IntentService.onStartCommand(IntentService.java:141)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
	... 8 more`
